[0m16:05:53.951290 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029D7CB5F430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029D7BAB8550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029D7BAA7A90>]}


============================== 16:05:53.957595 | 828322d5-6136-4925-8edc-ec39924d3dfd ==============================
[0m16:05:53.957595 [info ] [MainThread]: Running with dbt=1.7.2
[0m16:05:53.958605 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\RG6139\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init jaffle_shop', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:05:53.961826 [debug] [MainThread]: Starter project path: C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\include\starter_project
[0m16:05:54.027686 [info ] [MainThread]: 
Your new dbt project "jaffle_shop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:05:54.030678 [info ] [MainThread]: Setting up your profile.
[0m16:55:38.022615 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002746F40F3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002746E3715B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002746E36F250>]}


============================== 16:55:38.026604 | 1069d6f5-bb84-415e-bc59-7d4e5edfceba ==============================
[0m16:55:38.026604 [info ] [MainThread]: Running with dbt=1.7.2
[0m16:55:38.028599 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\RG6139\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init test', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:55:38.031590 [debug] [MainThread]: Starter project path: C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\include\starter_project
[0m16:55:38.080079 [info ] [MainThread]: 
Your new dbt project "test" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:55:38.086041 [info ] [MainThread]: Setting up your profile.
[0m16:56:08.258433 [error] [MainThread]: Encountered an error:

[0m16:56:08.264267 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\cli\requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\cli\requires.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\task\init.py", line 344, in run
    self.setup_profile(profile_name)
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\task\init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\task\init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\task\init.py", line 165, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\dbt\task\init.py", line 115, in generate_target_from_input
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "C:\Users\RG6139\AppData\Local\Programs\Python\Python38\lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m16:56:08.272244 [debug] [MainThread]: Command `dbt init` failed at 16:56:08.271248 after 30.32 seconds
[0m16:56:08.273242 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002746F40F3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027403E47A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027403E479A0>]}
[0m16:56:08.274240 [debug] [MainThread]: Flushing usage events
[0m16:58:27.160485 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000226B0A5E400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000226AF9BC580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000226AF9B0220>]}


============================== 16:58:27.168465 | 8dbae753-97f8-4055-a69f-7cd94caf7114 ==============================
[0m16:58:27.168465 [info ] [MainThread]: Running with dbt=1.7.2
[0m16:58:27.169461 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\RG6139\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:58:27.170492 [info ] [MainThread]: dbt version: 1.7.2
[0m16:58:27.172453 [info ] [MainThread]: python version: 3.8.6
[0m16:58:27.173450 [info ] [MainThread]: python path: C:\Users\RG6139\AppData\Local\Programs\Python\Python38\python.exe
[0m16:58:27.174448 [info ] [MainThread]: os info: Windows-10-10.0.19041-SP0
[0m16:58:30.660425 [info ] [MainThread]: Using profiles dir at C:\Users\RG6139\.dbt
[0m16:58:30.661391 [info ] [MainThread]: Using profiles.yml file at C:\Users\RG6139\.dbt\profiles.yml
[0m16:58:30.662412 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\RG6139\dbt-core\dbt-tutorial\dbt_project.yml
[0m16:58:30.666235 [info ] [MainThread]: adapter type: bigquery
[0m16:58:30.668233 [info ] [MainThread]: adapter version: 1.7.2
[0m16:58:30.668998 [info ] [MainThread]: Configuration:
[0m16:58:30.669997 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m16:58:30.670995 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m16:58:30.672256 [info ] [MainThread]: Required dependencies:
[0m16:58:30.674253 [debug] [MainThread]: Executing "git --help"
[0m16:58:30.790942 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone             Clone a repository into a new directory\n   init              Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add               Add file contents to the index\n   mv                Move or rename a file, a directory, or a symlink\n   restore           Restore working tree files\n   rm                Remove files from the working tree and from the index\n   sparse-checkout   Initialize and modify the sparse-checkout\n\nexamine the history and state (see also: git help revisions)\n   bisect            Use binary search to find the commit that introduced a bug\n   diff              Show changes between commits, commit and working tree, etc\n   grep              Print lines matching a pattern\n   log               Show commit logs\n   show              Show various types of objects\n   status            Show the working tree status\n\ngrow, mark and tweak your common history\n   branch            List, create, or delete branches\n   commit            Record changes to the repository\n   merge             Join two or more development histories together\n   rebase            Reapply commits on top of another base tip\n   reset             Reset current HEAD to the specified state\n   switch            Switch branches\n   tag               Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch             Download objects and refs from another repository\n   pull              Fetch from and integrate with another repository or a local branch\n   push              Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:58:30.791971 [debug] [MainThread]: STDERR: "b''"
[0m16:58:30.791971 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:58:30.793934 [info ] [MainThread]: Connection:
[0m16:58:30.794931 [info ] [MainThread]:   method: oauth
[0m16:58:30.795929 [info ] [MainThread]:   database: engie-b2c-cloud
[0m16:58:30.795929 [info ] [MainThread]:   execution_project: engie-b2c-cloud
[0m16:58:30.796950 [info ] [MainThread]:   schema: x_mca_tests
[0m16:58:30.797948 [info ] [MainThread]:   location: EU
[0m16:58:30.798920 [info ] [MainThread]:   priority: interactive
[0m16:58:30.799918 [info ] [MainThread]:   maximum_bytes_billed: None
[0m16:58:30.800937 [info ] [MainThread]:   impersonate_service_account: None
[0m16:58:30.800937 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m16:58:30.801937 [info ] [MainThread]:   job_retries: 1
[0m16:58:30.802931 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m16:58:30.803907 [info ] [MainThread]:   job_execution_timeout_seconds: 300
[0m16:58:30.804904 [info ] [MainThread]:   keyfile: None
[0m16:58:30.805903 [info ] [MainThread]:   timeout_seconds: 300
[0m16:58:30.806924 [info ] [MainThread]:   refresh_token: None
[0m16:58:30.807897 [info ] [MainThread]:   client_id: None
[0m16:58:30.809891 [info ] [MainThread]:   token_uri: None
[0m16:58:30.809891 [info ] [MainThread]:   dataproc_region: None
[0m16:58:30.811887 [info ] [MainThread]:   dataproc_cluster_name: None
[0m16:58:30.812926 [info ] [MainThread]:   gcs_bucket: None
[0m16:58:30.813881 [info ] [MainThread]:   dataproc_batch: None
[0m16:58:30.816874 [info ] [MainThread]: Registered adapter: bigquery=1.7.2
[0m16:58:30.817871 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m16:58:30.818893 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:58:39.857523 [debug] [MainThread]: BigQuery adapter: Got an error when attempting to create a bigquery client: 'Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
  '
[0m16:58:39.857523 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m16:58:39.859559 [info ] [MainThread]: [31m2 checks failed:[0m
[0m16:58:39.861144 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\RG6139\dbt-core\dbt-tutorial\dbt_project.yml> not found

[0m16:58:39.862143 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  Runtime Error
    
    dbt encountered an error while trying to read your profiles.yml file.
    
    Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
    

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m16:58:39.866158 [debug] [MainThread]: Command `dbt debug` failed at 16:58:39.866158 after 12.82 seconds
[0m16:58:39.867163 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m16:58:39.868128 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000226B0A5E400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000226C550EB80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000226C5523580>]}
[0m16:58:39.869153 [debug] [MainThread]: Flushing usage events
[0m14:57:52.373472 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001903390F400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001903286B7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019032861F10>]}


============================== 14:57:52.377319 | 1ce4baf3-b265-41dc-8899-9d617f7d52cd ==============================
[0m14:57:52.377319 [info ] [MainThread]: Running with dbt=1.7.2
[0m14:57:52.378666 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\RG6139\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:57:52.379697 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\RG6139\dbt-core\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:57:52.381690 [debug] [MainThread]: Command `dbt run` failed at 14:57:52.381690 after 0.07 seconds
[0m14:57:52.382687 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001903390F400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001902F7FA880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019032835F40>]}
[0m14:57:52.383660 [debug] [MainThread]: Flushing usage events
[0m15:01:37.283834 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022976F9F3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022975EB3A30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022975EB3A60>]}


============================== 15:01:37.287830 | 0a5107cb-495d-4eff-833b-5e914333607e ==============================
[0m15:01:37.287830 [info ] [MainThread]: Running with dbt=1.7.2
[0m15:01:37.288820 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\RG6139\\dbt-core\\dbt-tutorial', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:01:37.289849 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\RG6139\dbt-core\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:01:37.291844 [debug] [MainThread]: Command `dbt run` failed at 15:01:37.291844 after 0.01 seconds
[0m15:01:37.292841 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022976F9F3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022972E9A9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022975EC59D0>]}
[0m15:01:37.292841 [debug] [MainThread]: Flushing usage events
[0m15:05:18.376576 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022205E20430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022204D82640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022204D6C160>]}


============================== 15:05:18.380567 | af357875-e551-4c02-aba8-47491f433b68 ==============================
[0m15:05:18.380567 [info ] [MainThread]: Running with dbt=1.7.2
[0m15:05:18.381574 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\RG6139\\dbt-core\\dbt-tutorial', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:05:18.382606 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\RG6139\dbt-core\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:05:18.385568 [debug] [MainThread]: Command `dbt run` failed at 15:05:18.384600 after 0.07 seconds
[0m15:05:18.385568 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022205E20430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022204D932B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022204D46400>]}
[0m15:05:18.386603 [debug] [MainThread]: Flushing usage events
[0m15:06:11.060166 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2876A0400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D286602670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2865F2C10>]}


============================== 15:06:11.065152 | 634f1da4-3ed9-4900-8373-53a380fd9b55 ==============================
[0m15:06:11.065152 [info ] [MainThread]: Running with dbt=1.7.2
[0m15:06:11.066149 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\RG6139\\dbt-core\\dbt-tutorial', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:06:11.068150 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\RG6139\dbt-core\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:06:11.070849 [debug] [MainThread]: Command `dbt run` failed at 15:06:11.070849 after 0.07 seconds
[0m15:06:11.071846 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2876A0400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D286611070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2865C6EE0>]}
[0m15:06:11.072877 [debug] [MainThread]: Flushing usage events
